const inventoryItems = [
  // === WEAPONS ===
  { name: "Iron Sword", type: "weapon", subtype: "sword", desc: "A basic sword used for training.", attack: 10, rarity: "Common" },
  { name: "Flame Saber", type: "weapon", subtype: "sword", desc: "Infused with flame energy.", attack: 25, rarity: "Rare" },
  { name: "Moonlit Dagger", type: "weapon", subtype: "dagger", desc: "Silent but deadly.", attack: 15, rarity: "Uncommon" },
  { name: "Jade Staff", type: "weapon", subtype: "staff", desc: "Preferred by sages.", attack: 20, rarity: "Uncommon" },
  { name: "Lightning Blade", type: "weapon", subtype: "sword", desc: "Crackles with lightning.", attack: 30, rarity: "Epic" },
  { name: "Dual Daggers", type: "weapon", subtype: "dagger", desc: "Light and lethal.", attack: 18, rarity: "Uncommon" },
  { name: "Crimson Saber", type: "weapon", subtype: "sword", desc: "Blood-forged edge.", attack: 28, rarity: "Rare" },
  { name: "Mystic Staff", type: "weapon", subtype: "staff", desc: "Used by enlightened monks.", attack: 22, rarity: "Rare" },
  { name: "Bronze Sword", type: "weapon", subtype: "sword", desc: "An ancient relic.", attack: 16, rarity: "Uncommon" },
  { name: "Wind Piercer", type: "weapon", subtype: "dagger", desc: "Cuts through wind.", attack: 20, rarity: "Rare" },
  { name: "Spiritblade", type: "weapon", subtype: "sword", desc: "Spiritual energy flows within.", attack: 33, rarity: "Epic" },
  { name: "Stone Club", type: "weapon", subtype: "staff", desc: "Heavy and crude.", attack: 12, rarity: "Common" },
  { name: "Sunfang", type: "weapon", subtype: "sword", desc: "Radiates sunlight.", attack: 35, rarity: "Legendary" },
  { name: "Spectral Dagger", type: "weapon", subtype: "dagger", desc: "Wields ghostly energy.", attack: 21, rarity: "Epic" },
  { name: "Serpent Staff", type: "weapon", subtype: "staff", desc: "Crafted from snake bone.", attack: 24, rarity: "Rare" },
  { name: "Azure Edge", type: "weapon", subtype: "sword", desc: "Shimmers blue.", attack: 27, rarity: "Rare" },
  { name: "Obsidian Knife", type: "weapon", subtype: "dagger", desc: "Made of volcanic glass.", attack: 23, rarity: "Rare" },
  { name: "Lunar Cane", type: "weapon", subtype: "staff", desc: "Draws power from the moon.", attack: 26, rarity: "Epic" },
  { name: "Gilded Sword", type: "weapon", subtype: "sword", desc: "Royalty's weapon.", attack: 32, rarity: "Legendary" },
  { name: "Wraith Dagger", type: "weapon", subtype: "dagger", desc: "Phases through armor.", attack: 29, rarity: "Epic" },

  // === ARMORS ===
  { name: "Initiate Robe", type: "armor", desc: "Simple robe for new cultivators.", defense: 5, rarity: "Common" },
  { name: "Flameproof Robe", type: "armor", desc: "Protects against fire.", defense: 8, rarity: "Uncommon" },
  { name: "Qi-Infused Robe", type: "armor", desc: "Boosts Qi regeneration.", defense: 7, rarity: "Uncommon" },
  { name: "Windweave Robe", type: "armor", desc: "Light and agile.", defense: 6, rarity: "Common" },
  { name: "Stoneweave Robe", type: "armor", desc: "Heavy and protective.", defense: 10, rarity: "Rare" },
  { name: "Stormguard Robe", type: "armor", desc: "Blocks lightning damage.", defense: 9, rarity: "Rare" },
  { name: "Bloodwoven Robe", type: "armor", desc: "Boosts attack at cost of defense.", defense: 4, rarity: "Uncommon" },
  { name: "Moonshadow Robe", type: "armor", desc: "Grants stealth bonuses.", defense: 7, rarity: "Rare" },
  { name: "Sunsilk Robe", type: "armor", desc: "Radiates warmth.", defense: 6, rarity: "Uncommon" },
  { name: "Frosthide Robe", type: "armor", desc: "Wards off cold.", defense: 8, rarity: "Uncommon" },
  { name: "Void Robe", type: "armor", desc: "Shrouds the wearer in shadows.", defense: 11, rarity: "Epic" },
  { name: "Heavenly Robe", type: "armor", desc: "Made from divine thread.", defense: 15, rarity: "Legendary" },
  { name: "Gilded Robe", type: "armor", desc: "Gold-lined elegance.", defense: 13, rarity: "Epic" },
  { name: "Ironthread Robe", type: "armor", desc: "Threaded with steel.", defense: 12, rarity: "Rare" },
  { name: "Spirit Cloak", type: "armor", desc: "Ghostly protection.", defense: 10, rarity: "Rare" },
  { name: "Nightshroud", type: "armor", desc: "Conceals movement.", defense: 9, rarity: "Uncommon" },
  { name: "Emerald Robe", type: "armor", desc: "Green silk of the valley.", defense: 7, rarity: "Uncommon" },
  { name: "Ash Robe", type: "armor", desc: "Worn by wandering monks.", defense: 6, rarity: "Common" },
  { name: "Celestial Vest", type: "armor", desc: "Blessed by stars.", defense: 14, rarity: "Legendary" },
  { name: "Dragonhide Robe", type: "armor", desc: "Forged from drake skin.", defense: 16, rarity: "Legendary" },

  // === PILLS ===
  { name: "Minor Qi Pill", type: "pill", desc: "Restores 100 Qi.", effect: { qi: 100 }, materials: ["Spirit Herb"], rarity: "Common" },
  { name: "Health Pill", type: "pill", desc: "Restores 50 HP.", effect: { health: 50 }, materials: ["Red Lotus"], rarity: "Common" },
  { name: "Speed Pill", type: "pill", desc: "Boosts speed by 10.", effect: { speed: 10 }, materials: ["Wind Leaf"], rarity: "Uncommon" },
  { name: "Major Qi Pill", type: "pill", desc: "Restores 300 Qi.", effect: { qi: 300 }, materials: ["Spirit Root", "Dragon Grass"], rarity: "Rare" },
  { name: "Ironbody Pill", type: "pill", desc: "Boosts defense.", effect: { defense: 15 }, materials: ["Stone Heart"], rarity: "Rare" },
  { name: "Vitality Pill", type: "pill", desc: "Boosts health regen.", effect: { regen: 10 }, materials: ["Sun Herb"], rarity: "Uncommon" },
  { name: "Agility Pill", type: "pill", desc: "Boosts dodge rate.", effect: { dodge: 5 }, materials: ["Swift Bloom"], rarity: "Uncommon" },
  { name: "Clarity Pill", type: "pill", desc: "Boosts focus.", effect: { focus: 20 }, materials: ["Mind Lotus"], rarity: "Uncommon" },
  { name: "Blood Pill", type: "pill", desc: "Heals 100 HP.", effect: { health: 100 }, materials: ["Crimson Root"], rarity: "Rare" },
  { name: "Mystic Pill", type: "pill", desc: "Boosts all stats slightly.", effect: { all: 5 }, materials: ["Celestial Herb"], rarity: "Rare" },
  { name: "Phoenix Pill", type: "pill", desc: "Revives from near death.", effect: { health: 200 }, materials: ["Phoenix Feather"], rarity: "Epic" },
  { name: "Essence Pill", type: "pill", desc: "Boosts Qi limit.", effect: { qiLimit: 50 }, materials: ["Essence Crystal"], rarity: "Epic" },
  { name: "Lightning Pill", type: "pill", desc: "Boosts lightning resistance.", effect: { resist: "lightning" }, materials: ["Thunder Leaf"], rarity: "Uncommon" },
  { name: "Wind Rush Pill", type: "pill", desc: "Increases attack speed.", effect: { speed: 15 }, materials: ["Wind Lotus"], rarity: "Rare" },
  { name: "Stone Skin Pill", type: "pill", desc: "Reduces damage taken.", effect: { defense: 20 }, materials: ["Earth Core"], rarity: "Rare" },
  { name: "Soothing Pill", type: "pill", desc: "Removes negative effects.", effect: { cleanse: true }, materials: ["Moon Flower"], rarity: "Uncommon" },
  { name: "Dragon Pill", type: "pill", desc: "Greatly increases Qi.", effect: { qi: 500 }, materials: ["Dragon Heart"], rarity: "Legendary" },
  { name: "Golden Elixir", type: "pill", desc: "Boosts all attributes.", effect: { all: 10 }, materials: ["Gold Dew"], rarity: "Legendary" },
  { name: "Mind Focus Pill", type: "pill", desc: "Boosts clarity and focus.", effect: { focus: 30 }, materials: ["Wisdom Root"], rarity: "Rare" },
  { name: "Iron Soul Pill", type: "pill", desc: "Strengthens willpower.", effect: { will: 20 }, materials: ["Soul Ore"], rarity: "Rare" },

  // === TALISMANS ===
  { name: "Fire Ward Talisman", type: "talisman", desc: "Reduces fire damage.", uses: 1, effect: { resist: "fire" }, rarity: "Uncommon" },
  { name: "Water Seal Talisman", type: "talisman", desc: "Summons a wave.", uses: 1, damage: 35, rarity: "Rare" },
  { name: "Stone Guard Talisman", type: "talisman", desc: "Boosts defense.", uses: 1, effect: { defense: 15 }, rarity: "Rare" },
  { name: "Thunderclap Talisman", type: "talisman", desc: "AoE thunder damage.", uses: 1, damage: 45, rarity: "Epic" },
  { name: "Spirit Bind Talisman", type: "talisman", desc: "Freezes enemy movement.", uses: 1, effect: "bind", rarity: "Rare" },
  { name: "Mirror Veil Talisman", type: "talisman", desc: "Reflects next attack.", uses: 1, effect: "reflect", rarity: "Epic" },
  { name: "Earth Spike Talisman", type: "talisman", desc: "Damages all in line.", uses: 1, damage: 30, rarity: "Uncommon" },
  { name: "Wind Veil Talisman", type: "talisman", desc: "Increases dodge.", uses: 1, effect: { dodge: 10 }, rarity: "Uncommon" },
  { name: "Clarity Talisman", type: "talisman", desc: "Restores focus.", uses: 1, effect: { focus: 20 }, rarity: "Uncommon" },
  { name: "Dragon Flame Talisman", type: "talisman", desc: "Burns all enemies.", uses: 1, effect: "burn", damage: 50, rarity: "Legendary" },

  // === MARTIAL MANUALS ===
  { name: "Fang Swordplay", type: "manual", subtype: "sword", required: "sword", desc: "Aggressive slashes.", damage: 18, rarity: "Uncommon" },
  { name: "Tiger Palm", type: "manual", subtype: "palm", desc: "Ferocious palm strike.", damage: 20, rarity: "Uncommon" },
  { name: "Crane Boxing", type: "manual", subtype: "boxing", desc: "Graceful but deadly.", damage: 16, rarity: "Common" },
  { name: "Wave Staff", type: "manual", subtype: "staff", required: "staff", desc: "Sweeping water-style.", damage: 17, rarity: "Uncommon" },
  { name: "Crescent Dagger", type: "manual", subtype: "dagger", required: "dagger", desc: "Half-moon arc strike.", damage: 19, rarity: "Uncommon" },
  { name: "Dragon Fang", type: "manual", subtype: "sword", required: "sword", desc: "Piercing sword thrust.", damage: 22, rarity: "Rare" },
  { name: "Blazing Fist", type: "manual", subtype: "boxing", desc: "Flaming combo strikes.", damage: 21, rarity: "Rare" },
  { name: "Rolling Thunder Palm", type: "manual", subtype: "palm", desc: "Stuns on hit.", damage: 18, rarity: "Rare" },
  { name: "Storm Sweep Staff", type: "manual", subtype: "staff", required: "staff", desc: "AoE sweep.", damage: 20, rarity: "Rare" },
  { name: "Venom Stab", type: "manual", subtype: "dagger", required: "dagger", desc: "Poisons enemy.", damage: 17, rarity: "Uncommon" },
  { name: "Iron Will Boxing", type: "manual", subtype: "boxing", desc: "Strikes never falter.", damage: 15, rarity: "Common" },
  { name: "Shadow Fang Dagger", type: "manual", subtype: "dagger", required: "dagger", desc: "Dark stab.", damage: 18, rarity: "Rare" },
  { name: "Golden Staff Sweep", type: "manual", subtype: "staff", required: "staff", desc: "Heavy swing.", damage: 22, rarity: "Epic" },
  { name: "Serpent Palm", type: "manual", subtype: "palm", desc: "Sneaky twisting move.", damage: 16, rarity: "Uncommon" },
  { name: "Lion Roar Strike", type: "manual", subtype: "sword", required: "sword", desc: "Powerful sonic slash.", damage: 24, rarity: "Epic" },

  // === MOVEMENT MANUALS ===
  { name: "Windstep", type: "manual", subtype: "movement", desc: "Dash skill.", speedBonus: 18, rarity: "Rare" },
  { name: "Lightning Shift", type: "manual", subtype: "movement", desc: "Teleport short range.", speedBonus: 22, rarity: "Epic" },
  { name: "Feather Drift", type: "manual", subtype: "movement", desc: "Slow fall.", speedBonus: 12, rarity: "Uncommon" },
  { name: "Storm Step", type: "manual", subtype: "movement", desc: "Summons wind to boost movement.", speedBonus: 20, rarity: "Rare" }
];
