// inventory-data.js

const inventoryItems = [
  // === WEAPONS ===
  { name: "Iron Sword", type: "weapon", subtype: "sword", desc: "A basic sword used for training.", attack: 10 },
  { name: "Flame Saber", type: "weapon", subtype: "sword", desc: "Infused with flame energy.", attack: 25 },
  { name: "Moonlit Dagger", type: "weapon", subtype: "dagger", desc: "Silent but deadly.", attack: 15 },
  { name: "Jade Staff", type: "weapon", subtype: "staff", desc: "Preferred by sages.", attack: 20 },
  { name: "Lightning Blade", type: "weapon", subtype: "sword", desc: "Crackles with lightning.", attack: 30 },
  { name: "Dual Daggers", type: "weapon", subtype: "dagger", desc: "Light and lethal.", attack: 18 },
  { name: "Crimson Saber", type: "weapon", subtype: "sword", desc: "Blood-forged edge.", attack: 28 },
  { name: "Mystic Staff", type: "weapon", subtype: "staff", desc: "Used by enlightened monks.", attack: 22 },
  { name: "Bronze Sword", type: "weapon", subtype: "sword", desc: "An ancient relic.", attack: 16 },
  { name: "Wind Piercer", type: "weapon", subtype: "dagger", desc: "Cuts through wind.", attack: 20 },
  { name: "Spiritblade", type: "weapon", subtype: "sword", desc: "Spiritual energy flows within.", attack: 33 },
  { name: "Stone Club", type: "weapon", subtype: "staff", desc: "Heavy and crude.", attack: 12 },
  { name: "Sunfang", type: "weapon", subtype: "sword", desc: "Radiates sunlight.", attack: 35 },
  { name: "Spectral Dagger", type: "weapon", subtype: "dagger", desc: "Wields ghostly energy.", attack: 21 },
  { name: "Serpent Staff", type: "weapon", subtype: "staff", desc: "Crafted from snake bone.", attack: 24 },
  { name: "Azure Edge", type: "weapon", subtype: "sword", desc: "Shimmers blue.", attack: 27 },
  { name: "Obsidian Knife", type: "weapon", subtype: "dagger", desc: "Made of volcanic glass.", attack: 23 },
  { name: "Lunar Cane", type: "weapon", subtype: "staff", desc: "Draws power from the moon.", attack: 26 },
  { name: "Gilded Sword", type: "weapon", subtype: "sword", desc: "Royalty's weapon.", attack: 32 },
  { name: "Wraith Dagger", type: "weapon", subtype: "dagger", desc: "Phases through armor.", attack: 29 },

  // === ARMORS ===
  { name: "Initiate Robe", type: "armor", desc: "Simple robe for new cultivators.", defense: 5 },
  { name: "Flameproof Robe", type: "armor", desc: "Protects against fire.", defense: 8 },
  { name: "Qi-Infused Robe", type: "armor", desc: "Boosts Qi regeneration.", defense: 7 },
  { name: "Windweave Robe", type: "armor", desc: "Light and agile.", defense: 6 },
  { name: "Stoneweave Robe", type: "armor", desc: "Heavy and protective.", defense: 10 },
  { name: "Stormguard Robe", type: "armor", desc: "Blocks lightning damage.", defense: 9 },
  { name: "Bloodwoven Robe", type: "armor", desc: "Boosts attack at cost of defense.", defense: 4 },
  { name: "Moonshadow Robe", type: "armor", desc: "Grants stealth bonuses.", defense: 7 },
  { name: "Sunsilk Robe", type: "armor", desc: "Radiates warmth.", defense: 6 },
  { name: "Frosthide Robe", type: "armor", desc: "Wards off cold.", defense: 8 },
  { name: "Void Robe", type: "armor", desc: "Shrouds the wearer in shadows.", defense: 11 },
  { name: "Heavenly Robe", type: "armor", desc: "Made from divine thread.", defense: 15 },
  { name: "Gilded Robe", type: "armor", desc: "Gold-lined elegance.", defense: 13 },
  { name: "Ironthread Robe", type: "armor", desc: "Threaded with steel.", defense: 12 },
  { name: "Spirit Cloak", type: "armor", desc: "Ghostly protection.", defense: 10 },
  { name: "Nightshroud", type: "armor", desc: "Conceals movement.", defense: 9 },
  { name: "Emerald Robe", type: "armor", desc: "Green silk of the valley.", defense: 7 },
  { name: "Ash Robe", type: "armor", desc: "Worn by wandering monks.", defense: 6 },
  { name: "Celestial Vest", type: "armor", desc: "Blessed by stars.", defense: 14 },
  { name: "Dragonhide Robe", type: "armor", desc: "Forged from drake skin.", defense: 16 },

  // === PILLS ===
  { name: "Minor Qi Pill", type: "pill", desc: "Restores 100 Qi.", effect: { qi: 100 }, materials: ["Spirit Herb"] },
  { name: "Health Pill", type: "pill", desc: "Restores 50 HP.", effect: { health: 50 }, materials: ["Red Lotus"] },
  { name: "Speed Pill", type: "pill", desc: "Boosts speed by 10.", effect: { speed: 10 }, materials: ["Wind Leaf"] },
  { name: "Major Qi Pill", type: "pill", desc: "Restores 300 Qi.", effect: { qi: 300 }, materials: ["Spirit Root", "Dragon Grass"] },
  { name: "Ironbody Pill", type: "pill", desc: "Boosts defense.", effect: { defense: 15 }, materials: ["Stone Heart"] },
  { name: "Vitality Pill", type: "pill", desc: "Boosts health regen.", effect: { regen: 10 }, materials: ["Sun Herb"] },
  { name: "Agility Pill", type: "pill", desc: "Boosts dodge rate.", effect: { dodge: 5 }, materials: ["Swift Bloom"] },
  { name: "Clarity Pill", type: "pill", desc: "Boosts focus.", effect: { focus: 20 }, materials: ["Mind Lotus"] },
  { name: "Blood Pill", type: "pill", desc: "Heals 100 HP.", effect: { health: 100 }, materials: ["Crimson Root"] },
  { name: "Mystic Pill", type: "pill", desc: "Boosts all stats slightly.", effect: { all: 5 }, materials: ["Celestial Herb"] },
  { name: "Phoenix Pill", type: "pill", desc: "Revives from near death.", effect: { health: 200 }, materials: ["Phoenix Feather"] },
  { name: "Essence Pill", type: "pill", desc: "Boosts Qi limit.", effect: { qiLimit: 50 }, materials: ["Essence Crystal"] },
  { name: "Lightning Pill", type: "pill", desc: "Boosts lightning resistance.", effect: { resist: "lightning" }, materials: ["Thunder Leaf"] },
  { name: "Wind Rush Pill", type: "pill", desc: "Increases attack speed.", effect: { speed: 15 }, materials: ["Wind Lotus"] },
  { name: "Stone Skin Pill", type: "pill", desc: "Reduces damage taken.", effect: { defense: 20 }, materials: ["Earth Core"] },
  { name: "Soothing Pill", type: "pill", desc: "Removes negative effects.", effect: { cleanse: true }, materials: ["Moon Flower"] },
  { name: "Dragon Pill", type: "pill", desc: "Greatly increases Qi.", effect: { qi: 500 }, materials: ["Dragon Heart"] },
  { name: "Golden Elixir", type: "pill", desc: "Boosts all attributes.", effect: { all: 10 }, materials: ["Gold Dew"] },
  { name: "Mind Focus Pill", type: "pill", desc: "Boosts clarity and focus.", effect: { focus: 30 }, materials: ["Wisdom Root"] },
  { name: "Iron Soul Pill", type: "pill", desc: "Strengthens willpower.", effect: { will: 20 }, materials: ["Soul Ore"] },

  // === TALISMANS ===
  { name: "Fire Ward Talisman", type: "talisman", desc: "Reduces fire damage.", uses: 1, effect: { resist: "fire" } },
  { name: "Water Seal Talisman", type: "talisman", desc: "Summons a wave.", uses: 1, damage: 35 },
  { name: "Stone Guard Talisman", type: "talisman", desc: "Boosts defense.", uses: 1, effect: { defense: 15 } },
  { name: "Thunderclap Talisman", type: "talisman", desc: "AoE thunder damage.", uses: 1, damage: 45 },
  { name: "Spirit Bind Talisman", type: "talisman", desc: "Freezes enemy movement.", uses: 1, effect: "bind" },
  { name: "Mirror Veil Talisman", type: "talisman", desc: "Reflects next attack.", uses: 1, effect: "reflect" },
  { name: "Earth Spike Talisman", type: "talisman", desc: "Damages all in line.", uses: 1, damage: 30 },
  { name: "Wind Veil Talisman", type: "talisman", desc: "Increases dodge.", uses: 1, effect: { dodge: 10 } },
  { name: "Clarity Talisman", type: "talisman", desc: "Restores focus.", uses: 1, effect: { focus: 20 } },
  { name: "Dragon Flame Talisman", type: "talisman", desc: "Burns all enemies.", uses: 1, effect: "burn", damage: 50 },

  // === MARTIAL MANUALS ===
  { name: "Fang Swordplay", type: "manual", subtype: "sword", required: "sword", desc: "Aggressive slashes.", damage: 18 },
  { name: "Tiger Palm", type: "manual", subtype: "palm", desc: "Ferocious palm strike.", damage: 20 },
  { name: "Crane Boxing", type: "manual", subtype: "boxing", desc: "Graceful but deadly.", damage: 16 },
  { name: "Wave Staff", type: "manual", subtype: "staff", required: "staff", desc: "Sweeping water-style.", damage: 17 },
  { name: "Crescent Dagger", type: "manual", subtype: "dagger", required: "dagger", desc: "Half-moon arc strike.", damage: 19 },
  { name: "Dragon Fang", type: "manual", subtype: "sword", required: "sword", desc: "Piercing sword thrust.", damage: 22 },
  { name: "Blazing Fist", type: "manual", subtype: "boxing", desc: "Flaming combo strikes.", damage: 21 },
  { name: "Rolling Thunder Palm", type: "manual", subtype: "palm", desc: "Stuns on hit.", damage: 18 },
  { name: "Storm Sweep Staff", type: "manual", subtype: "staff", required: "staff", desc: "AoE sweep.", damage: 20 },
  { name: "Venom Stab", type: "manual", subtype: "dagger", required: "dagger", desc: "Poisons enemy.", damage: 17 },
  { name: "Iron Will Boxing", type: "manual", subtype: "boxing", desc: "Strikes never falter.", damage: 15 },
  { name: "Shadow Fang Dagger", type: "manual", subtype: "dagger", required: "dagger", desc: "Dark stab.", damage: 18 },
  { name: "Golden Staff Sweep", type: "manual", subtype: "staff", required: "staff", desc: "Heavy swing.", damage: 22 },
  { name: "Serpent Palm", type: "manual", subtype: "palm", desc: "Sneaky twisting move.", damage: 16 },
  { name: "Lion Roar Strike", type: "manual", subtype: "sword", required: "sword", desc: "Powerful sonic slash.", damage: 24 },

  // === MOVEMENT MANUALS ===
  { name: "Windstep", type: "manual", subtype: "movement", desc: "Dash skill.", speedBonus: 18 },
  { name: "Lightning Shift", type: "manual", subtype: "movement", desc: "Teleport short range.", speedBonus: 22 },
  { name: "Feather Drift", type: "manual", subtype: "movement", desc: "Slow fall.", speedBonus: 12 },
  { name: "Storm Step", type: "manual", subtype: "movement", desc: "Quick sidestep.", speedBonus: 14 },
  { name: "Mist Flow", type: "manual", subtype: "movement", desc: "Harder to hit.", speedBonus: 16 },
  { name: "Ripple Walk", type: "manual", subtype: "movement", desc: "Move on water.", speedBonus: 10 },
  { name: "Cobra Coil", type: "manual", subtype: "movement", desc: "Tactical backstep.", speedBonus: 13 },
  { name: "Serpent Slither", type: "manual", subtype: "movement", desc: "Evasive skill.", speedBonus: 19 },
  { name: "Comet Streak", type: "manual", subtype: "movement", desc: "Dash in a line.", speedBonus: 20 },
  { name: "Echo Step", type: "manual", subtype: "movement", desc: "Creates clone illusion.", speedBonus: 18 },
  { name: "Moonlight Glide", type: "manual", subtype: "movement", desc: "Elegant steps.", speedBonus: 17 },
  { name: "Falcon Dive", type: "manual", subtype: "movement", desc: "Drop from air.", speedBonus: 21 },
  { name: "Hawk Dash", type: "manual", subtype: "movement", desc: "Long horizontal dash.", speedBonus: 22 },
  { name: "Echo Walk", type: "manual", subtype: "movement", desc: "Evasion through mimicry.", speedBonus: 16 },
  { name: "Blur Step", type: "manual", subtype: "movement", desc: "Briefly vanish.", speedBonus: 23 },
  { name: "Wind Glide", type: "manual", subtype: "movement", desc: "Floaty movement.", speedBonus: 14 },
  { name: "Eagle Wings", type: "manual", subtype: "movement", desc: "Leap with great height.", speedBonus: 19 },
  { name: "Flash Flicker", type: "manual", subtype: "movement", desc: "Fast flick movement.", speedBonus: 25 },

  // === ELEMENTAL MANUALS ===
  { name: "Inferno Slash", type: "manual", subtype: "elemental", element: "fire", desc: "Fiery sword slash.", damage: 25 },
  { name: "Steam Burst", type: "manual", subtype: "elemental", element: "water", desc: "Scalding steam attack.", damage: 22 },
  { name: "Mud Trap", type: "manual", subtype: "elemental", element: "earth", desc: "Slows enemies.", damage: 15 },
  { name: "Thunder Step", type: "manual", subtype: "elemental", element: "lightning", desc: "Shock on dash.", damage: 20 },
  { name: "Wind Cutter", type: "manual", subtype: "elemental", element: "wind", desc: "Sharp air blade.", damage: 18 },
  { name: "Metal Crash", type: "manual", subtype: "elemental", element: "gold", desc: "Blunt metal wave.", damage: 21 },
  { name: "Flare Pillar", type: "manual", subtype: "elemental", element: "fire", desc: "Flaming column.", damage: 28 },
  { name: "Aqua Shield", type: "manual", subtype: "elemental", element: "water", desc: "Defensive water shield.", defense: 20 },
  { name: "Rock Blast", type: "manual", subtype: "elemental", element: "earth", desc: "Hurls rocks.", damage: 24 },
  { name: "Storm Call", type: "manual", subtype: "elemental", element: "lightning", desc: "Summons storm.", damage: 30 },
  { name: "Cyclone Dance", type: "manual", subtype: "elemental", element: "wind", desc: "Spinning wind slash.", damage: 23 },
  { name: "Iron Barrage", type: "manual", subtype: "elemental", element: "gold", desc: "Rapid metal strikes.", damage: 27 },
  { name: "Blazing Nova", type: "manual", subtype: "elemental", element: "fire", desc: "Fire explosion.", damage: 32 },
  { name: "Whirlpool Prison", type: "manual", subtype: "elemental", element: "water", desc: "Traps enemy in whirlpool.", damage: 26 }
];
